### ISSUE TITLE
Create findFriends operation

### ISSUE THREAD

**Issue by albertoruvel** [albertoruvel/dareu-web#5]
Create findFriends operation under Account resource

This operation must find all accepted friendships using a DTO, the user can be registered under user_id or requested_user_id and value accepted must be true

The DTO must have the following attributes
<ul>
   <li>Id</li>
   <li>Name</li>
   <li>Created dares count</li>
   <li>Video responses count</li>
</ul>

**Comment by roar109** [comment]
How I know the video count? it's the number of dare_response rows or dare_dare_response?

**Comment by albertoruvel** [comment]
Total count of dare_response where the user_id equals to user obtained by the security token
