### ISSUE TITLE
Create findFriend using a query

### ISSUE THREAD

**Issue by albertoruvel** [albertoruvel/dareu-web#6]
Create a findFriends operation under Account resource, the operations must receive a query string to find user friends containing that query string on their name

The operation must return the following response 

<ul>
   <li>Id</li>
   <li>Name</li>
   <li>Created dares count</li>
   <li>Video responses count</li>
</ul>

**Comment by roar109** [comment]
will overload the #5 with this functionality

**Comment by roar109** [comment]
If you send the name query param searches by name if it's not passed or empty return the complete list.
